#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/bindex
  
  rm -rf build/* 
  
  pySloc -L py  -X cover -X htmlcov -X dist -v $@ bindex tox.ini requirements.txt test_requirements.txt setup.py
else
  echo "DEV_BASE is not defined"
fi
