# projConfig.toml for bindex

[meta]
    version= '0.1.0'

[project]
    name = 'bindex'             # external name = distribution name
    package = 'bindex'             # internal name
    main_lang = 'py'
    version = '0.0.22'
    version_date = '2017-09-23'
    author = 'Jim Dixon'
    author_email = 'jdd@gmail.com'
    description='index content-keyed files'
    copyright = '2015-2017'
    dev_status = 'beta'
    license = 'mit'
    relpath = 'py/bindex'
    state = 'shared'
    url = 'https://jddixon.github.io/bindex'

[py]
    packages = ['bindex']
    package_dir = ['src']
    test_dir = 'tests'
    py_modules = []
    scripts=[]
    ext_modules = []

    # sdReq output
    distshare = []
    requirements=['setuptools']
    test_requirements=[]

    # trove stuff is TBD


